### ISSUE TITLE
Rules or Roles?

### ISSUE THREAD

**Issue by ByteExceptionM** [NamelessMC/debug.namelessmc.com#49]
https://github.com/NamelessMC/debug.namelessmc.com/blob/62ac5afe4e264d33baf45c6e6ec730179d9e541d/src/components/sections/GroupSyncSection.vue#L26

![image](https://files.byteexception.eu/img/9HRP7h9UdB.png)

**Comment by Aberdeener** [comment]
"Rules" is correct!
On the Group Sync config page of StaffCP, theyre referred to as Rules
<img width="2498" alt="Screen Shot 2022-01-16 at 23 21 46" src="https://user-images.githubusercontent.com/26070412/149725045-2f59c0a5-b5ea-4cfc-a14f-2d035c95f077.png">

Thanks for asking
